# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.1.0

jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: '16.13'
      - run: node --version
  cicd-tests-and-lint:
    executor:
      name: node/default
    steps:
      - checkout
      # look for existing cache and restore if found
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install npm packages
          command: npm install
          # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Run Linter
          command: npm run lint
  deploy:
    executor:
      name: node/default
    steps:
      - run:
          name: CI Deployment
          command: curl "https://api.render.com/deploy/srv-cgfhclkeoogqfc5emsqg?key=oKdjsMSDupc"

workflows:
  build-test-deploy:
    jobs:
      - install-node
      - cicd-tests-and-lint:
          requires:
            - install-node
      - deploy:
          requires:
            - cicd-tests-and-lint